server:
  port: 25000

spring:
  application:
    name: gulimall-seckill

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  sentinel:
    transport:
      #配置sentinel dashboard地址
      dashboard: localhost:8080

    #开启feign对sentinel的支持
    feign:
      sentinel:
        enabled: true

  redis:
    host: 192.168.89.128
    port: 6379




  #配置异步任务线程池
  task:
    execution:
      pool:
        core-size: 5
        max-size: 50

  session:
    store-type: redis


#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
